<a href="https://colab.research.google.com/github/v-becerril/Valores_Nulos/blob/main/Actividad3_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Gastos y costos 20-22_limpio (Hoja 2020)**

In [42]:
df2020 = pd.read_excel("Gastos y costos 20-23.xlsx", sheet_name="2020", skiprows=5)
df2020.head(3)

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,GASTO,DESCRIPCION,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA,Columna1
0,2020-01-01,39408,BD20F436-72CC-4BE2-AD37-5999D71AA391,ARE080115PBA,ARSI RENTA SA DE CV,MAQUINARIA,NaN,"Descripción: REVOLVEDORA, Modelo: ULTRAMP9A, M...",1.0,0.0,2248.28,0.0,0.0,2248.28,16300.0,I,Vigente,NaN,14051.72
1,2020-01-01,0001010100750847116902,85AEAC2E-6395-44A0-9CB9-754D06893375,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,490.0,78.40,0.0,0.0,568.40,568.4,I,Vigente,NaN,0.00
2,2020-01-01,0001010100752163714102,BD0DFE85-D776-41CB-9C5C-4FA7923E687A,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,195.0,31.20,0.0,0.0,226.20,226.2,I,Vigente,NaN,0.00

In [43]:
#Hacer una copia de la base de datos original
df_2020 = df2020.copy()

In [44]:
#Identificar valores nulos por columna
valores_nulos=df_2020.isnull().sum()
valores_nulos

FECHA             0
FOLIO           189
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO          2502
DESCRIPCION       0
TC              391
IMPORTE          34
IVA             268
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              1
STATUS            0
POLIZA         3321
Columna1          0
dtype: int64

In [45]:
#Eliminar columnas innecesarias
#axis = 1 para columnas
#axis = 0 para filas
df_2020.drop(['Columna1'], axis=1)

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,GASTO,DESCRIPCION,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA
0,2020-01-01,39408,BD20F436-72CC-4BE2-AD37-5999D71AA391,ARE080115PBA,ARSI RENTA SA DE CV,MAQUINARIA,NaN,"Descripción: REVOLVEDORA, Modelo: ULTRAMP9A, M...",1.0,0.00,2248.28,0.0,0.0,2248.28,16300.00,I,Vigente,NaN
1,2020-01-01,0001010100750847116902,85AEAC2E-6395-44A0-9CB9-754D06893375,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,490.00,78.40,0.0,0.0,568.40,568.40,I,Vigente,NaN
2,2020-01-01,0001010100752163714102,BD0DFE85-D776-41CB-9C5C-4FA7923E687A,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,195.00,31.20,0.0,0.0,226.20,226.20,I,Vigente,NaN
3,2020-01-01,3663,EF4504D6-830D-415C-AF03-80CF54C5E28E,PSS120625C86,PROMOTORA DE SERVICIOS Y SOLUCIONES EMPRESARIA...,HONORARIOS CONTABLES,NaN,HONORARIOS CONTABLES\nDEL MES DE ENERO DEL 2020.,1.0,10694.25,1711.08,0.0,0.0,12405.33,12405.33,I,Vigente,NaN
4,2020-01-01,2849,EC2F4AA4-BA64-4E2E-A5B7-4EBBE042D6D3,ENA7006081P0,ELECTROTERMICA NACIONAL SA DE CV,COMPRAS,NaN,Pago,1.0,0.00,NaN,0.0,0.0,0.00,0.00,P,Vigente,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3337,2020-12-01,125834,80BCB1D8-673F-495B-9C2A-4AC9F9CB38E5,SQS110113MU0,SERVICIO QUINTANA SUR S.A DE C.V,COMBUSTIBLE,G VTA,32011 MAGNA,1.0,129.79,20.21,0.0,0.0,150.00,150.00,I,Vigente,NaN
3338,2020-12-01,37652,D4C7C1FB-03A7-4046-A2BD-03EBE7DA861E,PSQ790724C90,"CIA. PERIODISTICA DEL SOL DE QUERETARO, S.A. D...",PUBLICIDAD,G VTA,82101504-PUBLICIDAD EN PERIODICOSCALOR Y CONTROL,1.0,2284.80,365.57,0.0,0.0,2650.37,2650.37,I,Vigente,NaN
3339,2020-12-01,160,FFCEE7D4-1F38-4D44-BE02-EB042DAACEE7,SQX981027RY5,"SUPER Q, S. A. DE C. V.",ALIMENTOS,G VTA,REF VICTORIA GROSELLA 3 LT PET NR,1.0,163.79,26.21,0.0,0.0,190.00,190.00,I,Vigente,NaN
3340,2020-12-01,634875,8DFF4F01-2F8B-4085-B116-05A314108B02,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,G FINA,COMISIONES E INTERESES,1.0,0.00,0.00,0.0,0.0,0.00,0.00,I,Vigente,NaN
3341,2020-12-01,1044477,F18225D6-4024-4F03-A15A-D18917386D59,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,COMBUSTIBLE,G VTA,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,1.0,14889.29,0.00,0.0,0.0,14889.29,14889.29,I,Vigente,NaN

In [46]:
#Identificar valores nulos por columna
valores_nulos=df_2020.isnull().sum()
valores_nulos

FECHA             0
FOLIO           189
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO          2502
DESCRIPCION       0
TC              391
IMPORTE          34
IVA             268
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              1
STATUS            0
POLIZA         3321
Columna1          0
dtype: int64

In [47]:
#Sustituir valores nulos con promedio o media -IMPORTE-
df_2020["IMPORTE"]=df_2020["IMPORTE"].fillna(round(df_2020["IMPORTE"].mean(),1))

In [48]:
#Identificar valores nulos por columna
valores_nulos=df_2020.isnull().sum()
valores_nulos

FECHA             0
FOLIO           189
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO          2502
DESCRIPCION       0
TC              391
IMPORTE           0
IVA             268
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              1
STATUS            0
POLIZA         3321
Columna1          0
dtype: int64

In [49]:
#Sustituir valores nulos por un string en concreto
df_2020["GASTO"]=df_2020["GASTO"].fillna("No aplica")

In [51]:
#Sustituir valores nulos por un valor numérico en  concreto -TC-
df_2020["TC"]= df_2020["TC"].fillna(0)

In [53]:
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill") -FOLIO-
#Filtro por columnas
df_2020["FOLIO"] =df_2020["FOLIO"].fillna(method="ffill")

/tmp/ipython-input-1378225526.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_2020["FOLIO"] =df_2020["FOLIO"].fillna(method="ffill")

In [54]:
#Sustituir valores nulos por un valor numérico en  concreto -IVA-
df_2020["IVA"]= df_2020["IVA"].fillna(0)

In [55]:
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill") -TIPO-
#Filtro por columnas
df_2020["TIPO"] =df_2020["TIPO"].fillna(method="ffill")

/tmp/ipython-input-2614315237.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_2020["TIPO"] =df_2020["TIPO"].fillna(method="ffill")

In [61]:
#Sustituir valores nulos por valores no nulos hacia adelante "forward fill" ("ffill") -POLIZA-
# Convertir la columna a tipo texto, valores no convertibles se vuelven NaN
columna = ["POLIZA"]
df_2020[columna] = df_2020[columna].astype(str)
#Filtro por columnas
df_2020["POLIZA"] = df_2020["POLIZA"].fillna(method="ffill")

/tmp/ipython-input-409065985.py:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_2020["POLIZA"] = df_2020["POLIZA"].fillna(method="ffill")

In [62]:
#Identificar valores nulos por columna
df_2020.isnull().sum()

FECHA          0
FOLIO          0
UUID           0
RFC            0
PROVEEDOR      0
TIPO GASTO     0
GASTO          0
DESCRIPCION    0
TC             0
IMPORTE        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
TIPO           0
STATUS         0
POLIZA         0
Columna1       0
dtype: int64

In [63]:
#Convertir DataFrame a CSV
df_2020.to_csv("Gastos&Costos_2020.csv")

**Gastos y costos 20-22_limpio (Hoja 2021)**

In [28]:
df2021 = pd.read_excel("Gastos y costos 20-23.xlsx", sheet_name="2021", skiprows=3)
df2021.head(3)

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,DESCRIPCION,MP,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA
0,2021-01-01,0001010100750847116902,71B4C8B9-8DAA-47CC-AD47-9DD90AA5AF6B,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMISION COBRADA,PUE,1.0,490.00,78.40,0.0,0.0,568.4,568.4,I,Vigente,0
1,2021-01-01,0001010100752163714102,B8AEDE83-CC76-404C-A611-6B5A87BA561F,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMISION COBRADA,PUE,1.0,345.00,55.20,0.0,0.0,400.2,400.2,I,Vigente,0
2,2021-01-01,19788,19B9B2C2-DF58-E24D-B43A-3FC4D5A929E7,ESI9612311E7,"ELECTRONICOS Y SIMILARES, S.A. DE C.V.",COMPRAS,MOTO E7 PLUS AZUL 64GB 4RAM,PUE,1.0,3447.41,551.59,0.0,0.0,3999.0,3999.0,I,Vigente,0

In [29]:
#Hacer una copia del dataframe original
df_2021 = df2021.copy()

In [30]:
#Identificar valores nulos por columna
df_2021.isnull().sum()

FECHA             0
FOLIO           147
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
DESCRIPCION       0
MP              654
TC                0
IMPORTE           0
IVA               0
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              0
STATUS            0
POLIZA         2372
dtype: int64

In [31]:
#Indentificar valores nulos por dataframe
df_2021.isnull().sum().sum()

np.int64(3173)

In [32]:
#Identificar el número de datos y columnas
df_2021.shape

(3035, 18)

In [33]:
#Identificar el tipo de datos de las columnas que tienen valores nulos
df_2021.dtypes[df_2021.isnull().any()]

FOLIO     object
MP        object
POLIZA    object
dtype: object

In [34]:
# Convertir columnas a tipo texto, valores no convertibles se vuelven NaN
columnas = ["FOLIO","MP", "POLIZA"]
df_2021[columnas] = df_2021[columnas].astype(str)

In [35]:
#Conocimeinto de la columna 'FOLIO'(147 valores nulos).
#Número de valores únicos en la columna:
print(df_2021['FOLIO'].nunique())
# Lista de valores únicos
print(df_2021['FOLIO'].unique())

#Verificar si existe este folio 000
existe = "000" in df_2021["FOLIO"].values
print(existe)

#Sustituir los NA's con este folio para saber que se desconoce
df_2021["FOLIO"] = df_2021["FOLIO"].fillna("000")

2681
['0001010100750847116902' '0001010100752163714102' '19788' ... '11740'
 '747826' '1227374']
False

In [36]:
#Conocimeinto de la columna 'POLIZA'(2372 valores nulos).
#Número de valores únicos en la columna:
print(df_2021['POLIZA'].nunique())

#Sustituir los NA's leyenda "SIN INFORMACIÓN"
df_2021["POLIZA"] = df_2021["POLIZA"].fillna("SIN INFROMACIÓN")

190

In [37]:
#Conocimiento de la columna 'MP' (654 valores nulos)
#Número de valores únicos en la columna:
print(df_2021['MP'].nunique())
# Lista de valores únicos
print(df_2021['MP'].unique())

#Cuantos valores hay de cada valor único
conteo = df_2021['MP'].value_counts()
print(conteo)

#Saber cuantos proveedores hay de cada MP
resumen = df_2021.groupby(["PROVEEDOR", "MP"]).size().unstack(fill_value=0)
print(resumen)

#Sustituir los NA'S con los valores mayores de los proveedores dados de alta
# Paso 1: calcular el valor mayoritario de PUE/PPD por proveedor
mayoria = df_2021.groupby("PROVEEDOR")["MP"].apply(lambda x: x.dropna().mode()[0] if not x.dropna().empty else None)

# Paso 2: usar ese valor para rellenar los NaN en MP
df_2021["MP"] = df_2021.apply(
    lambda row: mayoria[row["PROVEEDOR"]] if pd.isna(row["MP"]) else row["MP"],
    axis=1
)

3
['PUE' 'PPD' 'nan']
MP
PUE    1344
PPD    1037
nan     654
Name: count, dtype: int64
MP                                                  PPD  PUE  nan
PROVEEDOR
ADALBERTO ISMAEL CRUZ VAZQUEZ                         0    1    0
ADAM MILO MEXICO SA DE CV                             1    0    1
ADT Private Security Services de México S.A. de...   10    2   11
AESA ARTICULOS ELECTRICOS, S.A. DE C.V.              79   26   36
AFASI SA DE CV                                        0    2    0
...                                                 ...  ...  ...
VIDRIOS Y CRISTALES DE QUERETARO, S.A. DE C.V.        1    0    1
WEST INSTRUMENTS DE MEXICO, S.A.                      0    1    0
WILCON INGENIERIA Y DIBUJO SA DE CV                  11    0   12
ZONA DIGITAL 83 SA DE CV                              0    1    0
ÁNGEL OLVERA PACHECO                                  0    1    0

[299 rows x 3 columns]

In [40]:
#Verificación de NA's y exportación de dataframe
df_2021.isnull().sum().sum()
df_2021.to_csv("Gastos&Costos_2021.csv")

**Gastos y costos 20-22_limpio (Hoja 2022)**

In [64]:
df2022= pd.read_excel("Gastos y costos 20-23.xlsx", sheet_name= "2022",  skiprows=3)
print(df2022.shape)
df2022.head(10)

(2577, 19)

,Fecha,Folio,UUID,RFC,Proveedor,TIPO GASTO,Descripción,MP,TC,Importe,IVA,RET ISR,RET IVA,Otros,TOTAL MX,TOTAL SAT,Tipo,Status,Poliza
0,2022-01-01,280108,9DA0E63F-1D47-441F-93D7-C2E05AE4D35E,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006876 18/36 de 03/12/...,PPD,1.0,5551.38,888.22,0.0,0.0,NaN,6439.6,6439.6,I,Vigente,PE02-ENE22
1,2022-01-01,280109,7E00E776-A839-4D57-B291-411109164B2F,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006877 18/36 de 03/12/...,PPD,1.0,5551.98,888.32,0.0,0.0,NaN,6440.3,6440.3,I,Vigente,PE03-ENE22
2,2022-01-01,007817297284,BB6585C1-3B54-4130-AFD0-1867C3764821,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,Servicios de Facturación,PUE,1.0,0.00,0.00,0.0,0.0,NaN,0.0,0.0,I,Vigente,NaN
3,2022-01-01,5595,B5E4B4EB-6C2F-11EC-BB9D-00155D014009,ZEGC530520V4A,CARLOS ENRIQUE ZERMEÑO GUTIERREZ,COMPRAS,Pago,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.0,0.0,P,Vigente,NaN
4,2022-01-01,5614,BB6756D1-6CCD-11EC-947D-00155D014407,ZEGC530520V4A,CARLOS ENRIQUE ZERMEÑO GUTIERREZ,COMPRAS,Pago,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.0,0.0,P,Vigente,NaN
5,2022-01-01,42862,21CDEC71-91AE-4EB4-91BD-58D80CED00AA,AAE6411055P8,"AESA ARTICULOS ELECTRICOS, S.A. DE C.V.",COMPRAS,Pago,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.0,0.0,P,Vigente,NaN
6,2022-01-01,383133,3EDABA79-5D03-2045-930C-6D380CEE72CD,AME860107KD9,"ASPEL DE MEXICO, SA DE CV",MTTO COMPUTO,Suscripción ASPEL-NOI Mensual 1 Usr(s),PUE,1.0,360.00,57.60,0.0,0.0,NaN,417.6,417.6,I,Vigente,PE01-ENE22
7,2022-01-01,156067,8BBABFFC-C605-45BD-A42D-ECD689399FE1,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,Pago,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.0,0.0,P,Vigente,NaN
8,2022-01-01,156068,7B887D28-F37E-40E5-8F75-2E9922543394,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,Pago,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.0,0.0,P,Vigente,NaN
9,2022-01-01,901060,69710F5D-5E9A-4014-A2CE-AA2DB313AF67,BPU7901018D4,"BEBIDAS PURIFICADAS, S. DE R.L. DE C.V.",ALIMENTOS,Epura 20 Lts Policarbonato,PUE,1.0,78.00,0.00,0.0,0.0,NaN,78.0,78.0,I,Vigente,PE125-ENE22

In [65]:
valores_nulos=df2022.isnull().sum()
valores_nulos

Fecha             0
Folio           102
UUID              0
RFC               0
Proveedor         0
TIPO GASTO        0
Descripción       0
MP              553
TC              636
Importe           0
IVA               0
RET ISR           0
RET IVA           0
Otros          2577
TOTAL MX          0
TOTAL SAT         0
Tipo              0
Status            0
Poliza          801
dtype: int64

In [66]:
#Crear una copia del df original
df_2022 = df2022.copy()

In [67]:
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill")
#Filtro por columnas
df_2022["Folio"] = df_2022["Folio"].fillna(method="ffill")

/tmp/ipython-input-597299442.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_2022["Folio"] = df_2022["Folio"].fillna(method="ffill")

In [68]:
#Sustitución de valores nulos de acuerdo a condicional de columna Descripción y MP (Pago = PAGO)
MP_NULL = df_2022['MP'].isna()
df_2022.loc[MP_NULL, 'MP'] = 'PAGO'

In [69]:
# Rellenar valores nulos de TC con 0
df_2022["TC"] = df_2022["TC"].fillna(0)

In [70]:
# Rellenar valores nulos de Poliza con "SIN POLIZA"
df_2022["Poliza"] = df_2022["Poliza"].fillna("SIN POLIZA")

In [71]:
# Eliminar la columna "Otros"
df_2022 = df_2022.drop(columns=["Otros"])

In [72]:
#Verificación de valores nulos en el df
df_2022.isnull().sum()

Fecha          0
Folio          0
UUID           0
RFC            0
Proveedor      0
TIPO GASTO     0
Descripción    0
MP             0
TC             0
Importe        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
Tipo           0
Status         0
Poliza         0
dtype: int64

In [73]:
#Exportación de base de datos limpio a csv
df_2022.to_csv("Gastos&Costos_2022.csv")

**Gastos y costos 20-23_limpio (Hoja 2023)**

In [74]:
# Carga de archivo
df2023 = pd.read_excel("Gastos y costos 20-23.xlsx", sheet_name="2023", skiprows=3)
print(df2023.columns)
print(df2023.shape)
df2023.head(5)

Index(['Fecha', 'Folio', 'UUID', 'RFC', 'Proveedor', 'TIPO GASTO',
       'Descripción', 'MP', 'FP', 'TC', 'Importe', 'IVA', 'RET ISR', 'RET IVA',
       'Otros', 'TOTAL MX', 'TOTAL SAT', 'Tipo', 'Status', 'Poliza'],
      dtype='object')
(397, 20)

,Fecha,Folio,UUID,RFC,Proveedor,TIPO GASTO,Descripción,MP,FP,TC,Importe,IVA,RET ISR,RET IVA,Otros,TOTAL MX,TOTAL SAT,Tipo,Status,Poliza
0,2023-01-01,31,49536321-60A4-523E-A32F-E8BDF5C2276E,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
1,2023-01-01,38,20FBB63B-D550-512F-9668-EEC6F983CEB7,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
2,2023-01-01,341932,DB8C4388-D4E0-4F0C-A09C-77C773257F44,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006876 30/36 de 03/12/...,PPD,99.0,1.0,5551.38,888.22,0.0,0.0,NaN,6439.60,6439.60,I,Vigente,PE01-ENE23
3,2023-01-01,341933,A81A63F5-D5EC-4601-803E-375AF9CC5021,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006877 30/36 de 03/12/...,PPD,99.0,1.0,5551.98,888.32,0.0,0.0,NaN,6440.30,6440.30,I,Vigente,PE02-ENE23
4,2023-01-01,342205,DCC10492-DE51-4C87-8430-5676FBF81931,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000009486 5/48 de 03/12/2...,PPD,99.0,1.0,8454.37,1352.70,0.0,0.0,NaN,9807.07,9807.07,I,Vigente,PE03-ENE23

In [75]:
#Identificar valores nulos por columna
valores_nulos=df2023.isnull().sum()
valores_nulos

Fecha            0
Folio           13
UUID             0
RFC              0
Proveedor        0
TIPO GASTO       8
Descripción      0
MP              71
FP              71
TC               0
Importe          0
IVA              0
RET ISR          0
RET IVA          0
Otros          397
TOTAL MX         0
TOTAL SAT        0
Tipo             0
Status           0
Poliza         115
dtype: int64

In [76]:
#Realizamos una copia del dataframe
df_2023 = df2023
df_2023.head(5)

,Fecha,Folio,UUID,RFC,Proveedor,TIPO GASTO,Descripción,MP,FP,TC,Importe,IVA,RET ISR,RET IVA,Otros,TOTAL MX,TOTAL SAT,Tipo,Status,Poliza
0,2023-01-01,31,49536321-60A4-523E-A32F-E8BDF5C2276E,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
1,2023-01-01,38,20FBB63B-D550-512F-9668-EEC6F983CEB7,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
2,2023-01-01,341932,DB8C4388-D4E0-4F0C-A09C-77C773257F44,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006876 30/36 de 03/12/...,PPD,99.0,1.0,5551.38,888.22,0.0,0.0,NaN,6439.60,6439.60,I,Vigente,PE01-ENE23
3,2023-01-01,341933,A81A63F5-D5EC-4601-803E-375AF9CC5021,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006877 30/36 de 03/12/...,PPD,99.0,1.0,5551.98,888.32,0.0,0.0,NaN,6440.30,6440.30,I,Vigente,PE02-ENE23
4,2023-01-01,342205,DCC10492-DE51-4C87-8430-5676FBF81931,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000009486 5/48 de 03/12/2...,PPD,99.0,1.0,8454.37,1352.70,0.0,0.0,NaN,9807.07,9807.07,I,Vigente,PE03-ENE23

In [77]:
#Sustituir valores nulos por valores no nulos hacia adelante  "forward fill" ("ffill")
#Filtro por columnas
df_2023["Folio"] = df_2023["Folio"].fillna(method="ffill")
df_2023["Proveedor"] = df_2023["Proveedor"].fillna(method="ffill")
df_2023["TIPO GASTO"] = df_2023["TIPO GASTO"].fillna(method="ffill")

/tmp/ipython-input-44386524.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_2023["Folio"] = df_2023["Folio"].fillna(method="ffill")
/tmp/ipython-input-44386524.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_2023["Proveedor"] = df_2023["Proveedor"].fillna(method="ffill")
/tmp/ipython-input-44386524.py:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_2023["TIPO GASTO"] = df_2023["TIPO GASTO"].fillna(method="ffill")

In [78]:
#Sustitución de valores nulos de acuerdo a condicional de columna Descripción y MP (Pago = PAGO)
MP_NULL = df_2023['MP'].isna()
df_2023.loc[MP_NULL, 'MP'] = 'PAGO'

#Sustitución de valores nulos de acuerdo a condicional de columna Descripción y FP (Pago = 00)
df_2023["FP"]= df_2023["FP"].fillna(00)
df_2023

display(df_2023.isnull().sum())

Fecha            0
Folio            0
UUID             0
RFC              0
Proveedor        0
TIPO GASTO       0
Descripción      0
MP               0
FP               0
TC               0
Importe          0
IVA              0
RET ISR          0
RET IVA          0
Otros          397
TOTAL MX         0
TOTAL SAT        0
Tipo             0
Status           0
Poliza         115
dtype: int64

In [79]:
#Eliminar columna completa 'Otros' sin valores
df_2023 = df_2023.drop(["Otros"], axis = 1)
df_2023

,Fecha,Folio,UUID,RFC,Proveedor,TIPO GASTO,Descripción,MP,FP,TC,Importe,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,Tipo,Status,Poliza
0,2023-01-01,31,49536321-60A4-523E-A32F-E8BDF5C2276E,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,PAGO,0.0,1.0,0.00,0.00,0.0,0.0,0.00,0.00,P,Vigente,NaN
1,2023-01-01,38,20FBB63B-D550-512F-9668-EEC6F983CEB7,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,PAGO,0.0,1.0,0.00,0.00,0.0,0.0,0.00,0.00,P,Vigente,NaN
2,2023-01-01,341932,DB8C4388-D4E0-4F0C-A09C-77C773257F44,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006876 30/36 de 03/12/...,PPD,99.0,1.0,5551.38,888.22,0.0,0.0,6439.60,6439.60,I,Vigente,PE01-ENE23
3,2023-01-01,341933,A81A63F5-D5EC-4601-803E-375AF9CC5021,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006877 30/36 de 03/12/...,PPD,99.0,1.0,5551.98,888.32,0.0,0.0,6440.30,6440.30,I,Vigente,PE02-ENE23
4,2023-01-01,342205,DCC10492-DE51-4C87-8430-5676FBF81931,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000009486 5/48 de 03/12/2...,PPD,99.0,1.0,8454.37,1352.70,0.0,0.0,9807.07,9807.07,I,Vigente,PE03-ENE23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2023-02-01,882974,3E97C399-6747-4BCA-8436-ED4B0933DF33,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,COMISIONES E INTERESES,PUE,3.0,1.0,0.00,0.00,0.0,0.0,0.00,0.00,I,Vigente,NaN
393,2023-02-01,053560,B7132758-F800-4797-B1D6-CC61AFFEE444,BPU7901018D4,BEBIDAS PURIFICADAS,ALIMENTOS,Epura 20 Lts Policarbonato,PUE,1.0,1.0,220.00,0.00,0.0,0.0,220.00,220.00,I,Vigente,NaN
394,2023-02-01,1092957089,D1E2DC1E-9FFB-46C6-82E4-B350B83CB6F7,BMN930209927,BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BA...,COMISION BANCARIA,SERVICIOS BANCARIOS,PUE,3.0,1.0,18071.52,682.40,0.0,0.0,18753.92,18753.92,I,Vigente,NaN
395,2023-02-01,1453820,6249FE27-6FA6-4EFB-910E-3CD67A0E29A1,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,GASOLINA,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,PUE,5.0,1.0,14472.32,0.00,0.0,0.0,14472.32,14472.32,I,Vigente,NaN
396,2023-02-01,18,439A9230-277E-5563-818C-7630B0E8D706,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,PAGO,0.0,1.0,0.00,0.00,0.0,0.0,0.00,0.00,P,Vigente,NaN

In [81]:
#Rellenar los valores nulos con nombre 'NONE' en la variable 'Poliza'
df_2023['Poliza'] = df_2023['Poliza'].fillna('NONE')
display(df_2023.isnull().sum())

Fecha          0
Folio          0
UUID           0
RFC            0
Proveedor      0
TIPO GASTO     0
Descripción    0
MP             0
FP             0
TC             0
Importe        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
Tipo           0
Status         0
Poliza         0
dtype: int64

In [82]:
#Pasar dataframe limpio a csv.
df_2023.to_csv("Gastos&Costos_2023.csv")

In [ ]:
#Descargar colab